<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Congratulations!</title>

    <style>
        h1 {
            font-family: serif, "Times New Roman", sans-serif;
            font-style: normal;
            height: 150px;
            width: 250px;
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            margin: auto;
        }

        .button {
            font-family: serif, "Times New Roman", sans-serif;
            font-style: normal;
            height: 50px;
            width: 250px;
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            margin: auto;
        }

    </style>

</head>
<body>
<h1 class = "h1">Машина удалена</h1>
<form action="/pageOfCarsForAdmin" method="GET" class = "button">
    <button type="submit">Вернуться к перечню машин</button>
</form>
</body>
</html>
