<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добро пожаловать!</title>
</head>
<body>
<div class="block">
    <h1>Добро пожаловать!</h1>

    <form>
        <a href="/signIn">Sign In</a>
    </form>

    <form>
        <a href="/signUp">Sign Up</a>
    </form>

</div>

</body>
</html>

<style>
    .block {
        height: 350px;
        width: 350px;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom:0;
        margin: auto;
    }
</style>